### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kato-0126** [kato-0126/furima-34515#9]
# URL
https://furima-34515.herokuapp.com/
# Basic認証のIDとパスワード
ID：test
パスワード：test
# 出品者用のメールアドレスとパスワード
メールアドレス：test@test
パスワード：tststs1
# 購入者用のメールアドレスとパスワード
メールアドレス：test@test2
パスワード：tststs1

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン状態の出品者以外のユーザーのみ、必要な情報を適切に入力すると、商品の購入ができるようにしましょう**
購入画面に進めず、エラー画面に遷移してしまいます

※上記により、関連する動作確認は次回以降とさせていただきます

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kato-0126** [comment]
修正いたしました。

**Comment by kato-0126** [comment]
> 修正いたしました。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/111019836-06e05480-8405-11eb-9715-7682e359a491.png)
